version: 2.1

# orbs
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.8.2

# jobs
jobs:
  build:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Run tests..."
          npm run test --if-present

  publish:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: moradhi1/weather-app
          tag: v1.0.2
      - docker/push:
          image: moradhi1/weather-app
          tag: v1.0.2

# workflow
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
